# Generated by Django 4.1.13 on 2024-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_url',
            field=models.URLField(default='https://medium.com/'),
            preserve_default=False,
        ),
    ]
