# Generated by Django 4.1.13 on 2024-11-17 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
