# Generated by Django 4.1.13 on 2024-11-19 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_userpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
